source 'https://github.com/CocoaPods/Specs.git'

target 'SwiftSample' do
  pod 'Webtrends-SDK/Core', '~>3.0'
  pod 'Webtrends-SDK/Optimize', '~>3.0'

end
target 'SwiftSampleWatch Extension' do
  pod 'Webtrends-SDK/Watch'
  platform :watchos, '2.0'
end
